import './sass/main.scss';
import './js/modal';
import './js/scroll-up';
import './js/firebase/firebase';
import './js/firebase/firebase';
import './js/API/module';
import './js/render/module';
//import './js/dropout';
import './js/localization/app';
